apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-world.fullname" . }}-frontend-config
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  app-config: |
    {{- .Values.frontend.config.appConfig | nindent 4 }}
  environment: {{ .Values.frontend.config.environment | quote }}
  log-level: {{ .Values.frontend.config.logLevel | quote }}

