{{- if .Values.backend }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-backend
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    testing-app: test
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}


