{{- if .Values.frontend }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-frontend
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.frontend.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}


